name: Lint, Build and Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3

      - name: 🎛 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16
          cache: 'yarn'

      - name: ⚙️ Install
        run: yarn

      - name: 🎨 Lint JS
        run: yarn lint:js

      - name: 🎨 Lint CSS
        run: yarn lint:css

      - name: 🎨 Lint Format
        run: yarn lint:format

      - name: 🎨 Lint Types
        run: yarn lint:types

      - name: 🛠 Build
        run: yarn build

      - name: 🎯 Test
        run: yarn test:unit

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/
