name: Build and deploy to GH Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency: deployment-${{ github.ref }}

env:
  CF_PROJECT_NAME: 'universalprofile-test-dapp'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
        id: extract_branch

      - name: 🛎️ Checkout
        uses: actions/checkout@v3

      - name: 🎛 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'yarn'

      - name: ⚙️ Install
        run: yarn

      - name: 🎨 Lint JS
        run: yarn lint:js

      - name: 🎨 Lint CSS
        run: yarn lint:css

      - name: 🎨 Lint Format
        run: yarn lint:format

      - name: 🎨 Lint Types
        run: yarn lint:types

      - name: 🛠 Build
        run: yarn build

      - name: 🎯 Test
        run: yarn test:unit

      - name: 'Deploy production'
        if: ${{ github.event.number == '' }}
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy --project-name "${CF_PROJECT_NAME}" .vercel/output/static

      - name: Deploy devnet (PR builds)
        if: ${{ github.event.number != '' }}
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy --project-name "${CF_PROJECT_NAME}" .vercel/output/static --branch "${{ steps.extract_branch.outputs.branch }}"
