name: Docker Build and Push

on:
  push:
    branches: [main]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  GCR_PROJECT: lukso-infrastructure-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.BACKEND_SA_GCR_KEY }}
          project_id: lukso-infrastructure-dev

      - run: |-
          gcloud --quiet auth configure-docker

      - name: Bump version
        run: |-
          APP_VERSION=$(git describe --tags --abbrev=0 | awk -F. '{OFS="."; $NF+=1; print $0}' | sed 's/v//')
          git config --global user.email "release@lukso.network"
          git config --global user.name "Release Bot"
          git tag -a $APP_VERSION -m "Release Version $APP_VERSION"

      - name: Build
        run: |-
          docker build \
            --tag "eu.gcr.io/$GCR_PROJECT/$REPO_NAME:$APP_VERSION" \
            .

      - name: Publish Image
        run: |-
          docker push "eu.gcr.io/$GCR_PROJECT/$REPO_NAME:$APP_VERSION"

      - name: Publish Helm Chart
        run: |
          cd charts/identity-provider && helm package . --app-version $APP_VERSION --version $APP_VERSION
          curl -L --data-binary "@identity-provider-$APP_VERSION.tgz" -u charts:${{ secrets.CHARTMUSEUM_PASSWORD_STAGING }} http://chartmuseum.staging.lukso.dev/api/charts
          cd ../..
          git push --set-upstream origin main
          git push --tags
