name: Docker Build and Push

on:
  push:
    branches: [main]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  GCR_PROJECT: lukso-infrastructure-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.BACKEND_SA_GCR_KEY }}
          project_id: lukso-infrastructure-dev

      - run: |-
          gcloud --quiet auth configure-docker

      - name: Bump version
        run: |-
          git config --global user.email "release@lukso.network"
          git config --global user.name "Release Bot"
          npm version patch -m ":arrow_up: v%s [skip ci]"
          APP_VERSION=$(node -pe "require('./package.json').version")
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Build
        run: |-
          docker build \
            --tag "eu.gcr.io/$GCR_PROJECT/$REPO_NAME:${{ env.APP_VERSION }}" \
            .

      - name: Publish Image
        run: |-
          docker push "eu.gcr.io/$GCR_PROJECT/$REPO_NAME:${{ env.APP_VERSION }}"

      - name: Publish Helm Chart
        run: |
          cd charts/$REPO_NAME && helm package . --app-version ${{ env.APP_VERSION }} --version ${{ env.APP_VERSION }}
          curl -L --data-binary "@$REPO_NAME-${{ env.APP_VERSION }}.tgz" -u charts:${{ secrets.CHARTMUSEUM_PASSWORD_STAGING }} http://chartmuseum.staging.lukso.dev/api/charts
          cd ../..
          git push --set-upstream origin main
          git push --tags
